### ISSUE TITLE
Difference in sound length

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#138] opened 2019-04-11 23:31 UTC
For https://github.com/phetsims/QA/issues/303.  Noticed when comparing Dev 26 to Dev 29.  The echoing sounds of the sliders goes on for much longer in the newer dev version.  If this is intentional, please close.
https://drive.google.com/file/d/1eQdFqj4kDxA_xrWlHzYn4rRGVZ2qluP9/view?usp=sharing

**Comment by jessegreenberg** [comment] 2019-04-11 23:35
Thanks @KatieWoe, I am not sure about sound. I think the newer one sounds nicer so it is likely intentional but @jbphet would know for sure.

**Comment by jbphet** [comment] 2019-04-12 19:57
Yes, this was intentional.  I had gotten feedback that the fade out was too abrupt in https://github.com/phetsims/ohms-law/issues/125#issuecomment-464863478, so I implemented a slower fade and change the algorithm to be exponential.  The intent is to make the fade long and subtle since the current continues to be present, and we didn't want to make it seem like something had stopped.

There are also notes about this change in the Feb 19 and Feb 26 design meeting notes in https://docs.google.com/document/d/1fQGxB6XWzBNXQ1mpy7ok02Qw9lgBZ5CS4-Jmdh2Ln1Q/edit#heading=h.6uwgze1cizq5

The most relevant commits are:

+ be4acc46b462adfbc7ecc18379fe73f33ec77202
+ c206dbd96a33967708e5f0b7dd7bbd238c3f9cb3

**Comment by jbphet** [comment] 2019-04-12 19:57
Closing, since this is the intended behavior.

**Closed by jbphet** 2019-04-12 19:57 UTC
Labels: type:question
