### ISSUE TITLE
Artifacts tracing out bottom part of the R when changing value

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/ohms-law#45] opened 2016-01-14 17:29 UTC
Test device: Personal Mac, and Dirac
Operating System: OSX 10.11
Browser: Safari 9.0.2
Problem description: When Voltage is at maximum value 9.0 V, slowly decreasing the value of Resistance produces a tracing artifact of the bottom part of the R as the character "R" decreases in size

Steps to reproduce: 
Place Voltage at Maximum value
Bring Resistance to Maximum value
Slowly decrease value of the Resistance

Severity: Low

Screenshots:
<img width="1232" alt="screen shot 2016-01-14 at 10 20 44 am" src="https://cloud.githubusercontent.com/assets/5631059/12332040/9b15c408-baa9-11e5-9f0d-2e9115ce03dc.png">

Troubleshooting information (do not edit):
Name: Ohm's Law
URL: http://phet.colorado.edu/sims/html/ohms-law/latest/ohms-law_en.html
Version: 1.2.0
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11) AppleWebKit/601.1.56 (KHTML, like Gecko) Version/9.0 Safari/601.1.56
Language: en-us
Window: 1240x712
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (2.1 INTEL-10.8.77)
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 16384x16384
OES_texture_float: true

**Comment by orejolaphet** [comment] 2016-01-14 17:31
Artifacts disappear once the Resistance reaches minimum value, also disappears once Voltage manipulated.

**Comment by orejolaphet** [comment] 2016-01-19 16:37
Related to the task https://github.com/phetsims/tasks/issues/474

**Comment by jbphet** [comment] 2016-02-16 23:34
This is a duplicate of #26, closing.

**Closed by jbphet** 2016-02-16 23:34 UTC
