### ISSUE TITLE
VO repeats 1 Ohms Law

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#145] opened 2019-05-29 15:38 UTC
For https://github.com/phetsims/QA/issues/327
I ran into an issue on the second slider while using VO for Mac 10.14.5.  When moving the slider, often the alert would be interrupted to say "1 Ohms Law" often repeatedly.  It did not occur on the first slider, and sometime moving the slider a larger amount caused this not to happen.  I did things like refreshed the sim and pressed escape after reading the description before manipulating the sliders to stop it, and was unable to reproduce for a bit afterwards.
https://drive.google.com/file/d/1BjUiY0T4XOubE2xpj1gQms6shiHcoHSh/view?usp=sharing

**Comment by jessegreenberg** [comment] 2019-05-29 15:42
That is very strange @KatieWoe. Did you notice this with the first RC?

**Comment by jessegreenberg** [comment] 2019-05-29 15:53
@KatieWoe how frequently are you able to reproduce this? I don't know what "1" is, but my guess is that it is either reading the browser Tab index then the page title or something.

**Comment by KatieWoe** [comment] 2019-05-29 16:33
I didn't see it in the first rc.  When it showed up it kept happening.  But after it stopped due to a refresh I was not able to reproduce again.  Tried a few times.

**Comment by jessegreenberg** [comment] 2019-05-29 18:32
OK thanks. @terracoda are you familiar with this at all and do you know what VO is trying to report here? Ill do some searching too to see if anything comes up, but my guess is this can probably be closed since it shows up with such low frequency.

**Comment by jessegreenberg** [comment] 2019-05-29 18:58
I did a quick search but didn't see anything like what we are seeing here. Removing my assignment but given https://github.com/phetsims/ohms-law/issues/145#issuecomment-497012648, I am inclined to close this issue with `wontfix`.

**Comment by terracoda** [comment] 2019-05-30 22:00
@jessegreenberg, I have no memory of ever hearing "1 Ohm's Law" while using voice over. I just had a quick listen and I didn't hear it.

I'm using an older version of Mac OS, though, 10.13.6

I agree Jesse, I think we can mark it as "won't fix".

**Comment by jessegreenberg** [comment] 2019-05-30 22:04
Thanks @terracoda, sounds good.

**Closed by jessegreenberg** 2019-05-30 22:04 UTC
Labels: type:bug
