### ISSUE TITLE
Low Performance on iPad Air 2

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#132] opened 2019-02-18 22:08 UTC
For https://github.com/phetsims/QA/issues/289
On iOS 12.1.4 iPad Air 2 the performance dropped significantly when using the sliders.  ?profiler showed as low as 13 fps.  Averaged around 20, could be as high as 40.

**Comment by jessegreenberg** [comment] 2019-02-19 03:03
I only have access to an iPad2, but I can confirm that the performance has degraded on that platform since the published version.

**Comment by jessegreenberg** [comment] 2019-02-19 03:14
I tried disabling the alerts, then all a11y, then sound (by muting in the navigation bar). The sim a bit got faster after doing each, but disabling a11y was by far the most effective.

**Comment by jessegreenberg** [comment] 2019-02-19 03:21
I tried disabling positioning of PDOM elements, but I didn't see any improvement.

**Comment by jessegreenberg** [comment] 2019-02-19 18:06
Ill check on performance in this version: https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.25/phet/ohms-law_en_phet.html?a11y to see if it has bad then or has degraded since.

**Comment by jessegreenberg** [comment] 2019-02-19 18:11
Difficult to say, performance might be a little better in that version, but not by much.

**Comment by jessegreenberg** [comment] 2019-02-19 18:16
Performance for me is equivalent to the performance of the published version of RIAW on my iPad2. @KatieWoe is that true for iOS 12.1.4 iPad Air 2 as well?

**Comment by KatieWoe** [comment] 2019-02-19 18:33
Does seem fairly comparable.  Maybe even a tad better in Ohm's Law

**Comment by jessegreenberg** [comment] 2019-02-19 19:00
Here is a thing from Chrome tools, I am not sure what I am looking at yet
![image](https://user-images.githubusercontent.com/6396244/53040059-8251c080-344e-11e9-8cab-57723c1d084d.png)

But I see a lot lf "setTextContent" and "setInnerContent". which probably indicates that is what is taking up time?

**Comment by jessegreenberg** [comment] 2019-02-19 19:00
Above is the call tree from 'onPointerMove'.

**Comment by jessegreenberg** [comment] 2019-02-19 20:22
I just noticed that performance in the a11y view is far worse than it used to be, not sure if it is related to this.

**Comment by jessegreenberg** [comment] 2019-02-20 00:14
> I just noticed that performance in the a11y view is far worse than it used to be, not sure if it is related to this.

It isn't related to this, see https://github.com/phetsims/chipper/issues/740

**Comment by jessegreenberg** [comment] 2019-02-20 00:57
When returning early from AccessibilityUtil.setTextContent, the performance improves a bit. This in combination with disabling sound gets the performance closer to the published version.

Here is the call tree now:
![image](https://user-images.githubusercontent.com/6396244/53058308-88609500-3480-11e9-827f-8003a859c185.png)

**Comment by jessegreenberg** [comment] 2019-02-20 01:02
Within that call tree I am seeing setAttributeToElement and setInputValue taking together ~30% of the time taken for the event (total 0.5 ms).
![image](https://user-images.githubusercontent.com/6396244/53058454-16d51680-3481-11e9-9c7e-4c0a0310cc74.png)

**Comment by jessegreenberg** [comment] 2019-03-17 21:54
Doing profiling with @twant and @zepumph, we tried to replace using innerHTML with textContent in AccessibilityUtil.setTextContent and discovered that the innerHTML is taking up a large amount of time relative to textContent.
![image](https://user-images.githubusercontent.com/6396244/54498431-a386bf00-48dd-11e9-81a2-8f2ca942ef9a.png)

![image](https://user-images.githubusercontent.com/6396244/54498436-b5686200-48dd-11e9-88f0-e3c5443346da.png)


These images show that innerHTML took up ~25% of the computation time during the test, while using textContent took up about 5%.

**Comment by jessegreenberg** [comment] 2019-03-20 19:03
We tried batching changes to PDOM elements in https://github.com/phetsims/scenery/issues/663, but discovered that it isn't giving us much of a performance benefit because inner content is actually not updating much more frequently than once per element per animation frame. So we should reconsider how to optimize.

**Comment by jessegreenberg** [comment] 2019-03-20 19:05
[I found this jsperf ](https://jsperf.com/innerhtml-vs-innertext/12)for innerHTML vs textContent vs innerText and I see that innerHTML is 99% slower, which matches our testing results above.
![image](https://user-images.githubusercontent.com/6396244/54711976-86dac900-4b21-11e9-83d7-fcaa7a4fbc94.png)

**Comment by jessegreenberg** [comment] 2019-03-20 19:21
I opened https://github.com/phetsims/scenery/issues/955 to see if we can use textContent more than innerHTML because it is faster. But the dynamic descriptions in this sim use innerHTML so we wont see a performance improvement from that issue unless we can get rid of the formatting tags in this sim.

**Comment by jessegreenberg** [comment] 2019-03-20 19:53
Here is another test that shows setting innerHTML is slower than setting innerText of a strong tag:
http://jsben.ch/yH5vq

The block test sets textContent of a `strong` tag under a `p`, and the second test sets innerHTML of a `p` to be `<strong>Test!</strong>`

**Comment by jessegreenberg** [comment] 2019-03-20 20:10
With this test, I proceeded with https://github.com/phetsims/scenery/issues/955 and removed all formatting tags from a11y strings.
Before change, setTextContent takes 15% of running time.
![15](https://user-images.githubusercontent.com/6396244/54715494-fbb20100-4b29-11e9-94d7-691bf657cbd7.PNG)


After change, setTextContent takes 5% of running time:
![5](https://user-images.githubusercontent.com/6396244/54715472-f2289900-4b29-11e9-9fc0-bb5f9e58ae5b.PNG)

**Comment by jessegreenberg** [comment] 2019-03-20 21:04
A built version of OL with the changes in https://github.com/phetsims/ohms-law/issues/132#issuecomment-475008440 runs a little faster on an iPad2, but still slower than the published sim.

**Comment by jessegreenberg** [comment] 2019-03-20 21:12
In a number of screenshots above I see that `layout` and `Update Layer Tree` and `recalculate style` are all tied to AccessibilityUtil. When I click on AccessibilityUtil links in the dev tools, it takes me to the setting of textContent. I think that is the next place to investigate.

**Comment by jessegreenberg** [comment] 2019-03-28 16:23
In https://github.com/phetsims/scenery/issues/663 we found that `clip` will improve the performance of the PDOM while keeping the DOM interactive with AT. Performance improvement was found on my iPad2. Over to https://github.com/phetsims/QA/issues/303 to see if this benefit carries over to the iPad air.

**Comment by KatieWoe** [comment] 2019-04-12 00:09
Will need to wait a bit for the iPad Air 2's to come back, but I did a check on the iPad 2 with QA and can confirm that it looks much better now on that platform at least.

**Comment by KatieWoe** [comment] 2019-04-12 20:00
On an iOS 11 iPad Air 2 I saw that the average fps of the new dev version was about 5 to 10 fps higher than the average fps of the old dev version.

**Comment by jessegreenberg** [comment] 2019-04-12 20:29
Thanks @KatieWoe, that is an improvement. However, I also recently got an iPad Air 2 and was able to see that the performance is noticeably slower compared to the published version. But I also noticed that performance on iPad air 2 is substantially faster when the resistance is low. This indicates that a11y is no longer the performance bottleneck because a11y changes are not dependent on amount of resistance.

We should look into if anything about the dot visual rendering changed.

**Comment by jessegreenberg** [comment] 2019-04-16 15:51
I verified that the sim has the same poor performance with high resistance when both sound and accessibility are disabled.

**Comment by jessegreenberg** [comment] 2019-04-16 15:53
When I remove the `clipArea` on for the dots performance improves substantially.

**Comment by jessegreenberg** [comment] 2019-04-16 16:02
Changing the renderer to `canvas` helps performance mostly, but there is some slowdown when dragging the resistance thumb in areas of high resistance.

**Comment by jessegreenberg** [comment] 2019-04-16 16:22
I just noticed that `clipArea` is a recent addition since the last publication of this simulation so that is why the published sim is so much faster. I am going to change the implementation so that dots are contained within the wire shape without using clip shape.

**Comment by jessegreenberg** [comment] 2019-04-16 16:42
This is working great and performance is much faster on iPad Air 2. I am going to go ahead and close since I have access to an iPad air 2 now.

**Comment by jessegreenberg** [comment] 2019-04-16 20:39
To summarize what we looked into and changed to improve performance in this issue:

We discovered that DOM operations were taking up too much time in Chrome and Safari and so we we started https://github.com/phetsims/scenery/issues/663 to reduce the number of DOM changes that occur each animation frame. This included changes to innerHTML and other HTML attributes that were identified as slow in Chrome and Safari. We discovered that this was not as relevant to ohms-law because this sim doesn't have a large number of changes per frame. That work was in scenery and was not merged with master, but was kept on a branch.

We discovered that changing the PDOM styling so that elements are hidden with `clip` greatly improved performance on iPad 2 (https://github.com/phetsims/scenery/issues/663). But didn't have an impact on performance on an iPad Air 2. This change was still committed to master.

The final change was not related to a11y but to the `clipArea` used in this sim. By removing usage of `clipArea` with a large number of dots in the ResistorNode, the performance improved dramatically.

**Closed** 2019-04-16 20:40 UTC
Labels: type:performance
