### ISSUE TITLE
Mobile VO Does not allow slider movement

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ohms-law#131] opened 2019-02-18 22:02 UTC
For https://github.com/phetsims/QA/issues/289
From slack:
>Kathryn Woessner [2:49 PM]
>How do you adjust the sliders with mobile voice over?

>Jesse Greenberg [2:50 PM]
>While focus is on the slider, swipe your finger up to increment and down to decrement

>Kathryn Woessner [2:50 PM]
>I can't seem to do it

>Jesse Greenberg [2:51 PM]
>OK, what iOS?

>Kathryn Woessner [2:51 PM]
>iOS 12 latest

>Jesse Greenberg [2:51 PM]
>OK, interesting. Is VO making any sounds?

>Kathryn Woessner [2:56 PM]
>Yes.  Its focusing and behaving ok from everything else that I can tell so far (I just started) but I can;t move the sliders.

>Jesse Greenberg [2:57 PM]
>OK, bummer, it sounds like a bug

>Kathryn Woessner [2:57 PM]
>It also seems like you can focus on the word voltage or resistance, rather than the slider, but the box is just a dot
>I'll make an issue.

>Jesse Greenberg [2:57 PM]
>Thanks, that information might be relevant to the cause of the bug

**Comment by jessegreenberg** [comment] 2019-02-19 02:46
@KatieWoe could you please also put the iPad version in this issue?

**Comment by KatieWoe** [comment] 2019-02-19 15:42
iPad Air 2

**Comment by jessegreenberg** [comment] 2019-02-19 16:14
OK, thanks.

**Comment by jessegreenberg** [comment] 2019-02-19 16:18
Hmm, confirmed on my iPad2, on both dev version and master. Sorry @KatieWoe I swear I tested this before building the dev version. Ill try to figure out what changed.

**Comment by jessegreenberg** [comment] 2019-02-19 17:40
Aha! I found the related commit: https://github.com/phetsims/sun/commit/95e13cbbf1ae3e1d89ddbedb45da4f01687426f3#diff-325a03d9d9c2e5983737601dfe886b78

the event was being passed to the startDrag and endDrag from keydown/keyup related events but not from input/change events.

**Comment by KatieWoe** [comment] 2019-04-09 22:52
I am still having trouble with this in dev.29.  I can get each slider to move once or twice, but after that swiping moves focus to another part of the sim and doesn't move the slider.

**Comment by jessegreenberg** [comment] 2019-04-09 23:08
I just confirmed that it is working well on my iPad2. Over slack @KatieWoe and I said that tomorrow we will film or do a screenshare so I can see the gestures that are not working.

**Comment by KatieWoe** [comment] 2019-04-10 15:31
I did a bit more experimenting and I think the problem may have been that I was swiping too slowly and that my finger sometimes went over a different interactive piece that then gained focus.  May be worth looking at, but the gestures do seem to work.

**Comment by KatieWoe** [comment] 2019-04-10 15:56
>It also seems like you can focus on the word voltage or resistance, rather than the slider, but the box is just a dot

This does still occur

**Comment by jessegreenberg** [comment] 2019-04-10 23:16
> swiping too slowly and that my finger sometimes went over a different interactive piece that then gained focus. May be worth looking at, but the gestures do seem to work.

Thanks for doing more testing @KatieWoe. The gestures are designed by Apple so there isn't much more we can do to change things. It sounds like this is the correct behavior for VO.

> It also seems like you can focus on the word voltage or resistance, rather than the slider, but the box is just a dot

This is OK, in this case the virtual cursor is on the label for the slider. The reason this happens is that label and slider HTML must be adjacent (but not perfectly overlapping) for VO to handle events properly. As long as the virtual cursor can move from the label to the slider with gestures, everything is working correctly.

It sounds like everything is working OK so closing this issue.

**Closed by jessegreenberg** 2019-04-10 23:16 UTC
Labels: status:fixed-pending-testing, type:bug
