### ISSUE TITLE
Issue "?stringTest=double" text overlap

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/ohms-law#40] opened 2015-05-27 15:51 UTC
Testing for task https://github.com/phetsims/tasks/issues/245
Text overlaps for voltage and resistance
![screen shot 2015-05-27 at 9 49 22 am](https://cloud.githubusercontent.com/assets/5631059/7840711/eb187186-0455-11e5-8a80-ce9d51ec7936.png)

**Comment by pixelzoom** [comment] 2016-02-12 00:56
Duplicate of https://github.com/phetsims/ohms-law/issues/47 ?

**Comment by jbphet** [comment] 2016-02-16 23:15
Should now be fixed, will make sure that it is verified on the next release candidate.

**Comment by jbphet** [comment] 2016-02-24 17:01
Fixed, looks like this on v1.3.0-rc.2:

![ol-double-strings](https://cloud.githubusercontent.com/assets/3082831/13293603/8835d1e4-dadd-11e5-890d-e33c1f0ae4b6.PNG)

Closing.

**Closed by jbphet** 2016-02-24 17:01 UTC
Labels: type:i18n
