### ISSUE TITLE
New voltage labels fail to reposition on start-up

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ohms-law#129] opened 2019-02-16 06:21 UTC
Voltage labels get positioned above their battery while it is not full size. Once it is full-size, the labels move downward and are positioned on their battery 👍.

However, the VERY FIRST time you add the 4th, 5th, and 6th battery, their voltage labels incorrectly stay low between 0.0-0.1(ish) volts after which they will move up and work correctly for the rest of the sim's life. This must be done from a fresh sim, not from reset all.

This bug does not occur on the 1st, 2nd, and 3rd batteries.

BAD:

![image](https://user-images.githubusercontent.com/5863899/52894803-53e19600-316d-11e9-873d-715c06a773aa.png)

GOOD:

![image](https://user-images.githubusercontent.com/5863899/52894813-66f46600-316d-11e9-966d-c785da7604fc.png)

This has been a bug in this sim for a long time.....been keeping it in my back pocket I guess 🤷‍♂️.

Seen on Win 10. Chrome. For phetsims/QA/issues/289.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/ohms-law/1.4.0-dev.26/phet/ohms-law_en_phet.html
Version: 1.4.0-dev.26 2019-02-16 00:29:23 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
Language: en-US
Window: 1920x938
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
</details>

**Comment by KatieWoe** [comment] 2019-02-18 22:27
From slack:
>Kathryn Woessner [3:21 PM]
>I noticed this happen with a full battery (1.5).  Would this be a concern?
![outsidefull](https://user-images.githubusercontent.com/41024075/52979170-a8655b00-3391-11e9-87d8-43db61b1a55a.jpg)

>Jesse Greenberg [3:22 PM]
>I believe that is caused by https://github.com/phetsims/ohms-law/issues/127 and similar to https://github.com/phetsims/ohms-law/issues/129. Can you please test and see if it is possible to do that in master? Should be fixed

>Kathryn Woessner [3:25 PM]
>Doesn't look like I can anymore.

**Comment by jessegreenberg** [comment] 2019-02-18 22:32
Thanks @phet-steele and @KatieWoe. After #127 I can't reproduce https://github.com/phetsims/ohms-law/issues/129#issuecomment-464904885, but I can still reproduce https://github.com/phetsims/ohms-law/issues/129#issue-411035740

**Comment by jessegreenberg** [comment] 2019-02-18 22:40
Additional rounding needed to be done in BatteriesView which calculates the voltage remainder for the individual battery. Should be fixed.

**Comment by jessegreenberg** [comment] 2019-02-19 02:47
This is fixed, closing this issue.

**Closed by jessegreenberg** 2019-02-19 02:47 UTC
Labels: status:fixed-pending-testing, type:bug
